### ISSUE TITLE
Ctrl + Z ?

### ISSUE THREAD

**Issue by Uitalo** [krassowski/Anki-TouchScreen#1]
Ctrl + z for undo, is possible?

**Comment by krassowski** [comment]
Unlikely to work as Anki uses <kbd>Ctrl</kbd> + <kbd>z</kbd> for un-doing the card review - we would have a conflict, at least for some OSes. But I've just released a version supporting <kbd>Alt</kbd> + <kbd>z</kbd> as a substitute.

PS. You should be able to replace "alt" a "ctrl" in the source code if you insist.
